# -*- coding: utf-8 -*-
"""derivative n dimensions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DkZGX4iAmYVOfUVZ2hB-hvXnrnkDzck5
"""

objective_function2 = lambda x: x[0]**3 - x[1]**2 + x[2] + 5

def derivative(input_fuction, x):
  '''
  return derivative of function of x
  '''
  listX = [item for item in x]
  h = 0.1
  result = []
  for index , value in enumerate(x):
    # result[0] = (input_fuction(x + h , y) - input_fuction(x , y)) / h
    listX[index] =  listX[index] + h
    print(listX , x)
    result.append((input_fuction(listX) - input_fuction(x)) / h)
    listX = [item for item in x]

  # result ที่มีหลายมิติ
  return result

derivative(objective_function2 , [1,1,1])

